version: 2
updates:
- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - tobiasbrown
  ignore:
  - dependency-name: polished
    versions:
    - 4.0.5
    - 4.1.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
  - dependency-name: gatsby-plugin-catch-links
    versions:
    - 2.7.0
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.9.0
  - dependency-name: gatsby
    versions:
    - 2.24.91
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: gatsby-plugin-breadcrumb
    versions:
    - 10.0.0
- package-ecosystem: nuget
  directory: "/api"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - tobiasbrown
  ignore:
  - dependency-name: Sentry
    versions:
    - 2.1.8
    - 3.0.1
  - dependency-name: Sentry.AspNetCore
    versions:
    - 2.1.8
    - 3.0.1
  - dependency-name: Lamar
    versions:
    - 5.0.0
  - dependency-name: Lamar.Microsoft.DependencyInjection
    versions:
    - 5.0.0
