version: '3.3'
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 9002:5000
    volumes:
      - ./api:/app
  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - 9001:8000
    volumes:
      - ./ui/src:/app/src
